version: 2.1

orbs:
  win: circleci/windows@2.2.0 

jobs:
  build-with-windows:
    executor:
      name: win/default
      shell: bash.exe

    working_directory: ~/pandas_data_cleaner

    steps:
      - checkout

      - run: pip install Pillow
      - run: pip install --upgrade 'setuptools<45.0.0'
      - run: conda install pandas
      - run: pip install -U scikit-learn
      #- run: find / -name sklearn.utils._typedefs
      - run: find / -name "*typedefs*"
      #- run: pip install pyinstaller
      #- run: pip list
      #- run: pyinstaller pandas_data_cleaner.py --debug=imports --add-data "./images;images"
      #- run: mv dist dist-windows
      #- run: tar -cvzf dist-windows.tar.gz dist-windows

      #- store_artifacts:
      #    path: ~/pandas_data_cleaner/dist-windows.tar.gz

workflows:
  build-with-windows:
    jobs:
      - build-with-windows