version: 2.1

orbs:
  win: circleci/windows@2.2.0 

jobs:
  build-with-windows:
    executor:
      name: win/default
      shell: bash.exe

    working_directory: ~/pandas_data_cleaner

    steps:
      - checkout

      - run: pip install Pillow
      - run: pip install setuptools --upgrade
      - run: conda install pandas
      - run: pip install -U scikit-learn
      - run: pip install pyinstaller
      - run: pip list
      - run: pyinstaller --hidden-import="pkg_resources.py2_warn" --hidden-import="pkg_resources.markers" pandas_data_cleaner.py --add-data "./images;images"
      - run: mv dist dist-windows
      - run: tar -cvzf dist-windows.tar.gz dist-windows

      - store_artifacts:
          path: ~/pandas_data_cleaner/dist-windows.tar.gz

workflows:
  build-with-windows:
    jobs:
      - build-with-windows