version: 2.1

orbs:
  win: circleci/windows@2.2.0 

jobs:
  build-with-windows:
    executor:
      name: win/default
      shell: bash.exe

    working_directory: ~/pandas_data_cleaner

    steps:
      - checkout

      - run: pip install Pillow
      - run: pip install --upgrade 'setuptools<45.0.0'
      - run: pip install pandas==1.2.4
      - run: pip install scikit-learn==0.24.1
      - run: pip install pyinstaller
      - run: pip list
      - run: pyinstaller pandas_data_cleaner.py --debug=imports --add-data "./images;images"
      - run: tar -cvzf dist.tar.gz dist

      - store_artifacts:
          path: ~/pandas_data_cleaner/dist.tar.gz

workflows:
  build-with-windows:
    jobs:
      - build-with-windows