version: 2.1

jobs:
  windows-build:
    executor:
      - name: win/default
      - shell: command.exe
    steps:
      - checkout
      - run: pyinstaller pandas_data_cleaner.py --add-data "images;images" --add-data "sample_data;sample_data"
