version: 2.1

orbs:
  win: circleci/windows@2.2.0 

jobs:
  build-with-windows:
    executor:
      name: win/default
      shell: bash.exe

    working_directory: ~/pandas_data_cleaner

    steps:
      - checkout

      - run: pip install Pillow
      - run: conda install pandas
      - run: pip install -U scikit-learn
      - run: pip install pyinstaller
      - run: pyinstaller pandas_data_cleaner.py --add-data "./images;images"
      - run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"

      #- store_artifacts:
      #    path: ~/pandas_data_cleaner/build




workflows:
  build-with-windows:
    jobs:
      - build-with-windows